import argparse

args = argparse.ArgumentParser()
args.add_argument('--dim', type=int, default=512)
args.add_argument('--batch_size', type=int, default=1024)
args.add_argument('--epochs', type=int, default=1000)
args.add_argument('--valid_epochs', type=int, default=10)
args.add_argument('--lr', type=float, default=0.0001)
args.add_argument('--h_or_t', type=str, default='t')
args.add_argument('--dropout', type=float, default=0.4)
args.add_argument('--dataset', type=str, default='ICEWS14')
args.add_argument('--name', type=str, default=' ')
args.add_argument('--negative_size', type = int, default=16)
args.add_argument('--time_dim', type=int, default=64)
args.add_argument('--resume_epoch', type=int, default=-1)
args = args.parse_args()